# Generated by Django 2.2.3 on 2019-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=5, verbose_name='Gender of the subject')),
                ('citizenship', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, verbose_name='is the subject a citizen of Botswana?')),
                ('age', models.DateField(max_length=3, verbose_name='age of the subject')),
                ('literacy', models.CharField(choices=[('Literate', 'literate'), ('Illiterate', 'Illiterate')], max_length=20, verbose_name='is the subject literate or illiterate')),
            ],
        ),
    ]
