# Generated by Django 2.2 on 2019-07-03 18:35

from django.db import migrations, models
import questionnaire.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190703_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='age',
            field=models.DateField(validators=[questionnaire.validators.validate_age_eligability], verbose_name='age of the subject'),
        ),
    ]
